version: 2
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.16
    steps:
      - checkout
      - run: golangci-lint run -v -D errcheck
  build-node:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: "Build"
          command: ./wizard.sh -a
      - run:
          name: "Cleanup"
          command: rm -rf frontend/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  build-go:
    docker:
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: '~/project'
      - run:
          name: "Compile"
          command: ./wizard.sh -c
      - run:
          name: "Cleanup"
          command: |
            rm -rf frontend/build
            git checkout -- go.sum
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: '~/project'
      - run:
          name: "Release"
          command: ./wizard.sh -r $CIRCLE_TAG
workflows:
  version: 2
  build-workflow:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - build-node:
          filters:
            tags:
              only: /.*/
      - build-go:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
            - build-node
      - release:
          requires:
            - build-go
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
